// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: taskforge/v1/taskforge.proto

package taskforgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_SCHEDULED   TaskStatus = 2
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 3
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 4
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 5
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 7
	TaskStatus_TASK_STATUS_DEAD_LETTER TaskStatus = 8
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_SCHEDULED",
		3: "TASK_STATUS_QUEUED",
		4: "TASK_STATUS_RUNNING",
		5: "TASK_STATUS_COMPLETED",
		6: "TASK_STATUS_FAILED",
		7: "TASK_STATUS_CANCELLED",
		8: "TASK_STATUS_DEAD_LETTER",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_SCHEDULED":   2,
		"TASK_STATUS_QUEUED":      3,
		"TASK_STATUS_RUNNING":     4,
		"TASK_STATUS_COMPLETED":   5,
		"TASK_STATUS_FAILED":      6,
		"TASK_STATUS_CANCELLED":   7,
		"TASK_STATUS_DEAD_LETTER": 8,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_taskforge_v1_taskforge_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_taskforge_v1_taskforge_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{0}
}

type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_NORMAL      TaskPriority = 2
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 3
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "TASK_PRIORITY_UNSPECIFIED",
		1: "TASK_PRIORITY_LOW",
		2: "TASK_PRIORITY_NORMAL",
		3: "TASK_PRIORITY_HIGH",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"TASK_PRIORITY_LOW":         1,
		"TASK_PRIORITY_NORMAL":      2,
		"TASK_PRIORITY_HIGH":        3,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_taskforge_v1_taskforge_proto_enumTypes[1].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_taskforge_v1_taskforge_proto_enumTypes[1]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=taskforge.v1.TaskStatus" json:"status,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,6,opt,name=priority,proto3,enum=taskforge.v1.TaskPriority" json:"priority,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	RunAtUnix     int64                  `protobuf:"varint,9,opt,name=run_at_unix,json=runAtUnix,proto3" json:"run_at_unix,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,10,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,11,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	LastError     string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *Task) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Task) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Task) GetRunAtUnix() int64 {
	if x != nil {
		return x.RunAtUnix
	}
	return 0
}

func (x *Task) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Task) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Task) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority      TaskPriority           `protobuf:"varint,4,opt,name=priority,proto3,enum=taskforge.v1.TaskPriority" json:"priority,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	RunAtUnix     int64                  `protobuf:"varint,6,opt,name=run_at_unix,json=runAtUnix,proto3" json:"run_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CreateTaskRequest) GetRunAtUnix() int64 {
	if x != nil {
		return x.RunAtUnix
	}
	return 0
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=taskforge.v1.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type WatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskRequest) Reset() {
	*x = WatchTaskRequest{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskRequest) ProtoMessage() {}

func (x *WatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskRequest.ProtoReflect.Descriptor instead.
func (*WatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{9}
}

func (x *WatchTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskResponse) Reset() {
	*x = WatchTaskResponse{}
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskResponse) ProtoMessage() {}

func (x *WatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskforge_v1_taskforge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskResponse.ProtoReflect.Descriptor instead.
func (*WatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_taskforge_v1_taskforge_proto_rawDescGZIP(), []int{10}
}

func (x *WatchTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_taskforge_v1_taskforge_proto protoreflect.FileDescriptor

const file_taskforge_v1_taskforge_proto_rawDesc = "" +
	"\n" +
	"\x1ctaskforge/v1/taskforge.proto\x12\ftaskforge.v1\"\x92\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.taskforge.v1.TaskStatusR\x06status\x126\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x1a.taskforge.v1.TaskPriorityR\bpriority\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\b \x01(\x05R\vmaxAttempts\x12\x1e\n" +
	"\vrun_at_unix\x18\t \x01(\x03R\trunAtUnix\x12&\n" +
	"\x0fcreated_at_unix\x18\n" +
	" \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\v \x01(\x03R\rupdatedAtUnix\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\"\xd2\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x126\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x1a.taskforge.v1.TaskPriorityR\bpriority\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttempts\x12\x1e\n" +
	"\vrun_at_unix\x18\x06 \x01(\x03R\trunAtUnix\"<\n" +
	"\x12CreateTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskforge.v1.TaskR\x04task\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x0fGetTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskforge.v1.TaskR\x04task\"Z\n" +
	"\x10ListTasksRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.taskforge.v1.TaskStatusR\x06status\"=\n" +
	"\x11ListTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.taskforge.v1.TaskR\x05tasks\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x12CancelTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskforge.v1.TaskR\x04task\"\"\n" +
	"\x10WatchTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11WatchTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskforge.v1.TaskR\x04task*\xf9\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15TASK_STATUS_SCHEDULED\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x05\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\a\x12\x1b\n" +
	"\x17TASK_STATUS_DEAD_LETTER\x10\b*v\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_PRIORITY_LOW\x10\x01\x12\x18\n" +
	"\x14TASK_PRIORITY_NORMAL\x10\x02\x12\x16\n" +
	"\x12TASK_PRIORITY_HIGH\x10\x032\x95\x03\n" +
	"\vTaskService\x12O\n" +
	"\n" +
	"CreateTask\x12\x1f.taskforge.v1.CreateTaskRequest\x1a .taskforge.v1.CreateTaskResponse\x12F\n" +
	"\aGetTask\x12\x1c.taskforge.v1.GetTaskRequest\x1a\x1d.taskforge.v1.GetTaskResponse\x12L\n" +
	"\tListTasks\x12\x1e.taskforge.v1.ListTasksRequest\x1a\x1f.taskforge.v1.ListTasksResponse\x12O\n" +
	"\n" +
	"CancelTask\x12\x1f.taskforge.v1.CancelTaskRequest\x1a .taskforge.v1.CancelTaskResponse\x12N\n" +
	"\tWatchTask\x12\x1e.taskforge.v1.WatchTaskRequest\x1a\x1f.taskforge.v1.WatchTaskResponse0\x01BBZ@github.com/pablo-banker/taskforge/proto/taskforge/v1;taskforgev1b\x06proto3"

var (
	file_taskforge_v1_taskforge_proto_rawDescOnce sync.Once
	file_taskforge_v1_taskforge_proto_rawDescData []byte
)

func file_taskforge_v1_taskforge_proto_rawDescGZIP() []byte {
	file_taskforge_v1_taskforge_proto_rawDescOnce.Do(func() {
		file_taskforge_v1_taskforge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskforge_v1_taskforge_proto_rawDesc), len(file_taskforge_v1_taskforge_proto_rawDesc)))
	})
	return file_taskforge_v1_taskforge_proto_rawDescData
}

var file_taskforge_v1_taskforge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_taskforge_v1_taskforge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_taskforge_v1_taskforge_proto_goTypes = []any{
	(TaskStatus)(0),            // 0: taskforge.v1.TaskStatus
	(TaskPriority)(0),          // 1: taskforge.v1.TaskPriority
	(*Task)(nil),               // 2: taskforge.v1.Task
	(*CreateTaskRequest)(nil),  // 3: taskforge.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil), // 4: taskforge.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),     // 5: taskforge.v1.GetTaskRequest
	(*GetTaskResponse)(nil),    // 6: taskforge.v1.GetTaskResponse
	(*ListTasksRequest)(nil),   // 7: taskforge.v1.ListTasksRequest
	(*ListTasksResponse)(nil),  // 8: taskforge.v1.ListTasksResponse
	(*CancelTaskRequest)(nil),  // 9: taskforge.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil), // 10: taskforge.v1.CancelTaskResponse
	(*WatchTaskRequest)(nil),   // 11: taskforge.v1.WatchTaskRequest
	(*WatchTaskResponse)(nil),  // 12: taskforge.v1.WatchTaskResponse
}
var file_taskforge_v1_taskforge_proto_depIdxs = []int32{
	0,  // 0: taskforge.v1.Task.status:type_name -> taskforge.v1.TaskStatus
	1,  // 1: taskforge.v1.Task.priority:type_name -> taskforge.v1.TaskPriority
	1,  // 2: taskforge.v1.CreateTaskRequest.priority:type_name -> taskforge.v1.TaskPriority
	2,  // 3: taskforge.v1.CreateTaskResponse.task:type_name -> taskforge.v1.Task
	2,  // 4: taskforge.v1.GetTaskResponse.task:type_name -> taskforge.v1.Task
	0,  // 5: taskforge.v1.ListTasksRequest.status:type_name -> taskforge.v1.TaskStatus
	2,  // 6: taskforge.v1.ListTasksResponse.tasks:type_name -> taskforge.v1.Task
	2,  // 7: taskforge.v1.CancelTaskResponse.task:type_name -> taskforge.v1.Task
	2,  // 8: taskforge.v1.WatchTaskResponse.task:type_name -> taskforge.v1.Task
	3,  // 9: taskforge.v1.TaskService.CreateTask:input_type -> taskforge.v1.CreateTaskRequest
	5,  // 10: taskforge.v1.TaskService.GetTask:input_type -> taskforge.v1.GetTaskRequest
	7,  // 11: taskforge.v1.TaskService.ListTasks:input_type -> taskforge.v1.ListTasksRequest
	9,  // 12: taskforge.v1.TaskService.CancelTask:input_type -> taskforge.v1.CancelTaskRequest
	11, // 13: taskforge.v1.TaskService.WatchTask:input_type -> taskforge.v1.WatchTaskRequest
	4,  // 14: taskforge.v1.TaskService.CreateTask:output_type -> taskforge.v1.CreateTaskResponse
	6,  // 15: taskforge.v1.TaskService.GetTask:output_type -> taskforge.v1.GetTaskResponse
	8,  // 16: taskforge.v1.TaskService.ListTasks:output_type -> taskforge.v1.ListTasksResponse
	10, // 17: taskforge.v1.TaskService.CancelTask:output_type -> taskforge.v1.CancelTaskResponse
	12, // 18: taskforge.v1.TaskService.WatchTask:output_type -> taskforge.v1.WatchTaskResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_taskforge_v1_taskforge_proto_init() }
func file_taskforge_v1_taskforge_proto_init() {
	if File_taskforge_v1_taskforge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskforge_v1_taskforge_proto_rawDesc), len(file_taskforge_v1_taskforge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskforge_v1_taskforge_proto_goTypes,
		DependencyIndexes: file_taskforge_v1_taskforge_proto_depIdxs,
		EnumInfos:         file_taskforge_v1_taskforge_proto_enumTypes,
		MessageInfos:      file_taskforge_v1_taskforge_proto_msgTypes,
	}.Build()
	File_taskforge_v1_taskforge_proto = out.File
	file_taskforge_v1_taskforge_proto_goTypes = nil
	file_taskforge_v1_taskforge_proto_depIdxs = nil
}
